apiVersion: v1

kind: Service

metadata:

name: web-html

labels:

app: web-html

spec:

ports:

- nodePort:

31000

port: 80

targetPort: 80

selector:

app: web-html NodePort

type:

apiVersion: v1

kind: PersistentVolumeClaim

metadata:

name: web-pv-claim

labels:

app: web-html

spec:

accessModes:

- ReadWriteOnce

resources:

requests:

storage: 20Gi
